import json,hashlib,shutil,xml.etree.ElementTree as ET
from pathlib import Path
root=Path.cwd(); tmp=Path('/tmp/qualification-attempt4-v5-verification'); runtime=root/'artifacts/runtime'; f=runtime/'openttd-15.3-two-rollover-qualification-real-prelaunch-v5'; native=runtime/'openttd-15.3-two-rollover-qualification-real-attempt4'
load=lambda p:json.loads(p.read_text())
a=load(tmp/'postrun-audit.json');meta=load(f/'PRELAUNCH.json');lin=load(tmp/'postconsumption-lineage.json');s=load(native/'qualification-session.json');prod=a['production'];life=a['cleanup'];ev=life['endpoint_verification'];usage=dict(a['phase_usage']);guard=json.loads(a['final_guard']['response']);anchor=a['anchor'];final=a['final'];clock=a['clock']['samples']
counts={}
for name in ['original-lineage-endpoint','postconsumption','focused','ordinary']:
 suites=list(ET.parse(tmp/(name+'.xml')).getroot().iter('testsuite'));v={k:sum(int(x.attrib.get(k,0)) for x in suites) for k in ['tests','failures','errors','skipped']};v['passed']=v['tests']-v['skipped']-v['failures']-v['errors'];assert v['failures']==v['errors']==0;counts[name]=v
for name in ['ruff','format','typecheck-proof','typecheck-runtime-lineage']:
 assert ('All checks passed' in (tmp/(name+'.log')).read_text()) or (name=='format' and 'already formatted' in (tmp/(name+'.log')).read_text()),name
assert (tmp/'diff-check.log').read_text()==''
assert lin['next_native_attempt']==5 and not lin['reusable'] and prod['complete'] and prod['qualified_for_planning']
for filename in ['v5-persistent-before.json','attempt4-before-offline.json']:
 for p,d in load(tmp/filename).items():assert hashlib.sha256(Path(p).read_bytes()).hexdigest()==d,p
out=root/'artifacts/verification/openttd-15.3-two-rollover-qualification-v5-native-attempt4-postrun';assert not out.exists();out.mkdir(parents=True)
for p in tmp.iterdir():
 if p.is_file():shutil.copy2(p,out/p.name)
status='OPENTTD 15.3 REAL TWO-ROLLOVER QUALIFICATION ATTEMPT 4 UNDER V5 PASSED — QUALIFIED PRODUCTION READY FOR P08 ADAPTER DESIGN'
verification=dict(attempt_id=meta['attempt_id'],freeze=str(f),native_attempt=4,native_result='SUCCESS',overall_acceptance='PASS',cleanup='PASS',offline_verification='PASS',runtime_activity=dict(launches=1,connections=1,requests=a['totals'][0],retries=0,reconnects=0,resume=False),endpoint=ev,postconsumption_lineage=lin,tests=counts,quality='PASS',status=status)
(out/'verification.json').write_text(json.dumps(verification,indent=2)+'\n')
def sect(title,rows):return '## '+title+'\n\n'+'\n'.join(f'- {k}: {v}' for k,v in rows)+'\n\n'
def date(x):return f"{x['economy_year']:04}-{x['economy_month']:02}-{x['economy_day']:02} (native economy date {x['economy_date']})"
report='# Attempt 4 under V5 — final acceptance\n\n'+status+'\n\n'
report+=sect('Attempt',[('freeze',str(f/'PRELAUNCH.json')),('attempt ID',meta['attempt_id']),('native attempt',4),('checkpoint HEAD',meta['checkpoint_head']),('predecessors','Attempt 1 POST-LAUNCH FAILED; Attempt 2 POST-LAUNCH FAILED overall/native SUCCESS/offline FAIL; V3 PRELAUNCH FAILED 0/0/0; Attempt 3 under V4 POST-LAUNCH FAILED overall/native SUCCESS/offline PASS/endpoint cleanup FAIL'),('authorization','Exactly one real launch explicitly authorized in this session; no retry, reconnect or resume')])
report+=sect('Runtime',[('launches',1),('connections','1 encrypted secure Admin'),('retries',0),('reconnects',0),('duration',f"approximately {(native/'proof-evidence.json').stat().st_mtime-(native/'PRELAUNCH.json').stat().st_mtime:.1f} seconds, runtime evidence creation-to-finalization window; precise monotonic total not retained"),('process continuity','YES'),('connection continuity','YES'),('runtime/world/config/bridge continuity','YES'),('gameplay mutations',0)])
report+=sect('Economy',[('M0',date(clock[0])),('rollover 1',date(clock[1])+'; adjacent M0 → M1'),('M1','February 1950'),('rollover 2',date(clock[2])+'; adjacent M1 → M2'),('M2','March 1950'),('final guard',date(guard)+'; PASS'),('qualified month','February 1950'),('third rollover','NO')])
for title,obs,targets,lifetimes in [('M1 anchor',anchor,s['targets_anchor'],s['lifetimes_anchor']),('M2 final',final,s['targets_final'],s['lifetimes_final'])]:
 report+=sect(title,[('structural digest',obs['structural_world_digest']),('industries',obs['industry_count']),('T1 count' if title=='M1 anchor' else 'T2 count',len(targets)),('L1 count' if title=='M1 anchor' else 'L2 count',len(lifetimes)),('month coherence','PASS'),('structural observation','COMPLETE'),('target/lifetime identities','FINALIZED')])
report+=sect('Stability',[('T1 == T2','YES'),('target additions',0),('target removals',0),('lifetime changes',0),('lifetime/fingerprint stability','PASS; construction dates remain CALENDAR identity')])
report+=sect('Production',[('targets',len(s['targets_final'])),('records',len(prod['records'])),('requests',usage['production'][0]),('response bytes',usage['production'][1]),('production digest',prod['production_digest']),('complete','true'),('qualified_for_planning','true'),('source structural digest',prod['source_structural_world_digest']+'; EXACT final M2 digest'),('fresh M2 capture','YES; each target once; M2 economy brackets coherent'),('production_level','DEFERRED / NOT INCLUDED'),('station allocation','Native station allocation; not vehicle pickup or delivered throughput')])
report+=sect('Accounting',[('clock requests',usage['clock'][0]),('application requests',a['totals'][0]),('response bytes',a['totals'][1]),('query operations',a['totals'][2]),('lifecycle frames',6),('post-auth frames',a['frames']),('ceilings','304 / 1072 / 368080 / 9088 / 6 / 9094'),('independent phase ceilings','PASS; one continuous accounting object; no reset or budget borrowing'),('polling/deadline','1 second / 300 seconds; unchanged')])
report+=sect('Endpoint cleanup',[('owned process reaped','YES; returncode 0, quit requested and reaped'),('reservation released','YES'),('game UDP closed','YES'),('endpoint',f"127.0.0.1 game TCP/UDP {meta['game_port']}; secure Admin TCP {meta['admin_port']}"),('address family',ev['family']),('LISTEN present','NO'),('active connection present','NO'),('TIME_WAIT present','YES; client tuple '+str(ev['kernel_states'])),('immediate rebind attempted','NO'),('connection probe','NO'),('endpoint verifier result','PASS; '+ev['policy']),('arbitrary sleep/native retry','NONE')])
report+=sect('Cleanup',[('credential removed','YES; private bytes excluded from public evidence'),('workspace disposed','YES'),('source integrity','PASS'),('historical integrity','PASS'),('post-run integrity','PASS'),('native semantics / receipts / liveness','PASS')])
report+=sect('Post-consumption lineage',[(f'Attempt {i} historical','PASS') for i in range(1,5)]+[('V3 prelaunch historical','PASS; 0/0/0 remains PRELAUNCH'),('Attempts 1–4 reusable','NO'),('Attempt 4 reusable','NO'),('next native attempt',5),('historical vs next semantics','Independent; historical Attempt 4 matches V5 without deriving its successor')])
report+=sect('Offline acceptance',[('endpoint regressions','PASS'),('lineage','PASS'),('original V3 / retained Attempt 2 regressions','PASS'),('focused optional skips','PostgreSQL live smoke; separately gated P03 native launch; standalone tagged Squirrel interpreter'),('original regression batch',f"{counts['original-lineage-endpoint']['passed']} passed, {counts['original-lineage-endpoint']['skipped']} skipped"),('focused',f"{counts['focused']['passed']} passed, {counts['focused']['skipped']} skipped; 0 failures/errors"),('ordinary',f"{counts['ordinary']['passed']} passed, {counts['ordinary']['skipped']} skipped; serial; 0 failures/errors"),('post-consumption Attempt 4 tests','3 passed; historical validator does not consult current history; reuse rejected; successor 5 preserves historical identity'),('supplementary audit correction','Initial temporary test referenced nonexistent AttemptIdentity.native_attempt_id; validation itself passed. Corrected temporary assertion reads native ID from retained proof-evidence.json. Initial output retained in postconsumption-initial.log/xml; no source/freeze repair.'),('quality','PASS'),('overall final acceptance','PASS')])
report+=sect('Claim boundary',[('controlled qualification','PROVEN'),('real execution','PROVEN'),('qualified historical production','PROVEN'),('complete production','PROVEN'),('same-run provenance','PROVEN'),('P08','NO'),('atomic snapshot','NO'),('independent source','NONE')])
report+=sect('Historical integrity',[(name,'PASS; byte-identical') for name in ['V1','Attempt 1','V2','Attempt 2','V3','V4','Attempt 3','V5','complete raw proof','production Attempt 1/2','CONTEXT.md']]+[('Attempt 3 exact EADDRINUSE cause','UNKNOWN, unchanged; controlled TIME_WAIT reproduction does not prove original socket cause'),('Attempt 3 overall / retained qualification','FAILED / qualified_for_planning=false; unchanged')])
report+=sect('Tests',[(name,'PASS (focused and serial ordinary suite)') for name in ['endpoint','reservation','cleanup/lifecycle','lineage','prelaunch continuation','qualification','clock','lifetime','polling/accounting','coverage','production','structural/catalog/capability/inventory','bridge/protocol/transport','secure Admin','P03–P08']])
report+=sect('Quality',[(name,'PASS') for name in ['Ruff','format','applicable proof/runtime/lineage typecheck','git diff --check','whitespace audit','import boundary audit']]+[('source changes during execution','NONE'),('commit','NO'),('push','NO')])
report+='## Status\n\n'+status+'\n'
(out/'final-report.md').write_text(report)
lines=[hashlib.sha256(p.read_bytes()).hexdigest()+'  '+p.name for p in sorted(out.iterdir()) if p.is_file() and p.name!='artifact-manifest.sha256'];(out/'artifact-manifest.sha256').write_text('\n'.join(lines)+'\n')
print(out/'final-report.md');print(status)
