"""Used surface of pymonocypher 4.0.3.2's Cython extension (c_monocypher.pyx)."""

def x25519_public_key(secret_key: bytes) -> bytes: ...
def x25519(your_secret_key: bytes, their_public_key: bytes) -> bytes: ...
def lock(
    key: bytes, nonce: bytes, message: bytes, associated_data: bytes | None = ...
) -> tuple[bytes, bytes]: ...
def unlock(
    key: bytes, nonce: bytes, mac: bytes, message: bytes, associated_data: bytes | None = ...
) -> bytearray | None: ...

class IncrementalAuthenticatedEncryption:
    def __init__(self, key: bytes, nonce: bytes) -> None: ...
    def lock(self, message: bytes, associated_data: bytes | None = ...) -> tuple[bytes, bytes]: ...
    def unlock(
        self, mac: bytes, message: bytes, associated_data: bytes | None = ...
    ) -> bytearray | None: ...
